# -*- coding: utf-8 -*-
"""Limpieza de Datos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GxEvuk4C2ZrBlVj_FFVxZsY__hnI2z8T
"""

!pip install pandas
!pip install openpyxl
!pip install matplotlib

from google.colab import files

# Subir un archivo CSV a Google Colab
uploaded = files.upload()

import pandas as pd

# Datos que se utilizarán para el DataFrame
data = {
    'Nombre': ['Juan', 'María', 'Pedro', 'Lucía'],
    'Edad': [25, 30, 21, 28],
    'Puntuacion': [70, 85, 90, 80]
}

# Crear el DataFrame
dataframe = pd.DataFrame(data)

# Mostrar el DataFrame
print(dataframe)

import pandas as pd


# Mostrar una vista previa de los primeros registros del DataFrame
print("DataFrame original:")
print(dataframe.head())

# Calcular la media y la desviación estándar de las columnas numéricas
media = dataframe.mean()
desviacion_estandar = dataframe.std()

# Definir el umbral para identificar valores anómalos (por ejemplo, basado en la desviación estándar)
umbral = 2  # Puedes ajustar este valor según tus necesidades

# Filtrar los valores anómalos basados en la desviación estándar
dataframe_limpio = dataframe[(dataframe > (media - umbral * desviacion_estandar)) & (dataframe < (media + umbral * desviacion_estandar))]

# Mostrar una vista previa del DataFrame después de la limpieza
print("\nDataFrame después de la limpieza de datos anómalos:")
print(dataframe_limpio.head())