# -*- coding: utf-8 -*-
"""venta electrónica

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14UKFVYLVty2wFb8g-qZjAoNEodpFnI3D
"""

# from google.colab import files
# files.upload()

import pandas as pd

# Carga de datos desde el archivo CSV
data = pd.read_csv('ventas_electronica.csv')

# Tamaño del conjunto de datos
print("Tamaño del conjunto de datos:")
print(data.shape)

# Estadísticas descriptivas
print("\nEstadísticas descriptivas:")
print(data.describe())

import pandas as pd

# Carga de datos desde el archivo CSV
data = pd.read_csv('../../ventas_electronica.csv')

# Información general del conjunto de datos
print("Información general del conjunto de datos:")
print(data.info())

# Primeras filas del conjunto de datos
print("\nPrimeras filas del conjunto de datos:")
print(data.head())

# Resumen estadístico
print("\nResumen estadístico del conjunto de datos:")
print(data.describe())

# Valores únicos en cada columna
print("\nValores únicos en cada columna:")
for column in data.columns:
    unique_values = data[column].nunique()
    print(f"{column}: {unique_values} valores únicos")

# Comprobar valores faltantes
print("\nValores faltantes en el conjunto de datos:")
missing_values = data.isnull().sum()
print(missing_values)

import pandas as pd
import matplotlib.pyplot as plt

# Carga de datos desde el archivo CSV
data = pd.read_csv('ventas_electronica.csv')

# Visualización de los primeros registros del conjunto de datos
print("Primeras filas del conjunto de datos:")
print(data.head())

# Histogramas de las variables
data.hist(bins=20, figsize=(12, 8))
plt.show()